Task 1
Data splitting--> want 1. correct split
2. stratified by age
3. seed=42
4. keeping the eval_data always locked

In [2]:
#load data development and evaluation
from functions import *

In [3]:
#data splitting 80-20 keeping eval locked
#stratified by age
#seed=42
dev_data = pd.read_csv("../data/development_data.csv", index_col=0)
print("Development set", dev_data.shape, dev_data.head())
print("\n")
eval_data=pd.read_csv("../data/evaluation_data.csv", index_col=0)
print("Evaluation set (locked)", eval_data.shape,eval_data.head())
print(len(dev_data),len(eval_data))

Development set (456, 1003)            age             ethnicity sex  cg16867657  cg06639320  cg24724428  \
sample_id
GSM990554   79  Caucasian - European   M    0.672001    0.504461    0.331257
GSM990278   46    Hispanic - Mexican   M    0.555411    0.389214    0.160708
GSM990589   78  Caucasian - European   M    0.781318    0.554360    0.337578
GSM990323   46    Hispanic - Mexican   F    0.542491    0.435584    0.228723
GSM990116   59    Hispanic - Mexican   F    0.653190    0.466217    0.208453

           cg07553761  cg22454769  cg06784991  cg21572722  ...  cg17321954  \
sample_id                                                  ...
GSM990554    0.327287    0.572867    0.309496    0.444902  ...    0.174936
GSM990278    0.230875    0.464971    0.223665    0.381837  ...    0.154691
GSM990589    0.437668    0.645529    0.309615    0.505999  ...    0.213999
GSM990323    0.231709    0.493908    0.245836    0.424905  ...    0.198334
GSM990116    0.284740    0.592122    0.239320    0.434244  ...    0.147234

           cg17783401  cg26483332  cg22730412  cg14704921  cg12179661  \
sample_id
GSM990554    0.094635    0.163394    0.304777    0.093110    0.522947
GSM990278    0.043087    0.173311    0.343683    0.029271    0.496056
GSM990589    0.089760    0.173368    0.338127    0.066988    0.484525
GSM990323    0.121145    0.164312    0.394890    0.044809    0.510717
GSM990116    0.035716    0.156062    0.341784    0.024294         NaN

           cg16780603  cg00588614  cg13039082  cg16640358
sample_id
GSM990554    0.736352    0.262954    0.295386    0.350803
GSM990278    0.801962    0.291890    0.288421    0.318693
GSM990589    0.588307    0.276745    0.263589    0.344015
GSM990323    0.736712    0.287274    0.333076    0.303317
GSM990116    0.828072    0.256653    0.322450    0.370363

[5 rows x 1003 columns]


Evaluation set (locked) (100, 1003)            age             ethnicity sex  cg16867657  cg06639320  cg24724428  \
sample_id
GSM990599   65  Caucasian - European   F    0.713534    0.533543    0.338730
GSM989922   76  Caucasian - European   M    0.705395    0.472859    0.310131
GSM990306   63    Hispanic - Mexican   F    0.662773    0.481706    0.237187
GSM990320   59    Hispanic - Mexican   M    0.638065    0.456544    0.174587
GSM990002   71  Caucasian - European   F    0.695067    0.495763    0.276582

           cg07553761  cg22454769  cg06784991  cg21572722  ...  cg17321954  \
sample_id                                                  ...
GSM990599    0.364203    0.662077    0.291724    0.490470  ...    0.237585
GSM989922    0.358959    0.635802    0.287507         NaN  ...    0.206049
GSM990306    0.267787    0.602300    0.306610    0.453492  ...    0.189996
GSM990320    0.281471    0.614537    0.293233    0.436461  ...    0.169437
GSM990002    0.326186    0.662770    0.307118    0.405137  ...    0.176188

           cg17783401  cg26483332  cg22730412  cg14704921  cg12179661  \
sample_id
GSM990599    0.079218    0.165617    0.359383    0.085150    0.570230
GSM989922    0.096464    0.132663    0.280081    0.061219    0.536635
GSM990306    0.070674    0.182137    0.325564    0.052198    0.500524
GSM990320    0.064268    0.199800    0.317769    0.061953    0.528459
GSM990002    0.095870    0.184929    0.270476    0.047256    0.492331

           cg16780603  cg00588614  cg13039082  cg16640358
sample_id
GSM990599    0.800902    0.269018    0.290623    0.314786
GSM989922    0.744812    0.248199    0.262726    0.330051
GSM990306    0.725678    0.298588    0.334402    0.313727
GSM990320    0.748813    0.325457    0.329465    0.363478
GSM990002    0.792136    0.267520         NaN    0.346092

[5 rows x 1003 columns]
456 100

In [4]:
# Loading the eval and dev data through function
dev_data,eval_data=loading_files("../data/development_data.csv","../data/evaluation_data.csv")

Development set (456, 1003)            age             ethnicity sex  cg16867657  cg06639320  cg24724428  \
sample_id
GSM990554   79  Caucasian - European   M    0.672001    0.504461    0.331257
GSM990278   46    Hispanic - Mexican   M    0.555411    0.389214    0.160708
GSM990589   78  Caucasian - European   M    0.781318    0.554360    0.337578
GSM990323   46    Hispanic - Mexican   F    0.542491    0.435584    0.228723
GSM990116   59    Hispanic - Mexican   F    0.653190    0.466217    0.208453

           cg07553761  cg22454769  cg06784991  cg21572722  ...  cg17321954  \
sample_id                                                  ...
GSM990554    0.327287    0.572867    0.309496    0.444902  ...    0.174936
GSM990278    0.230875    0.464971    0.223665    0.381837  ...    0.154691
GSM990589    0.437668    0.645529    0.309615    0.505999  ...    0.213999
GSM990323    0.231709    0.493908    0.245836    0.424905  ...    0.198334
GSM990116    0.284740    0.592122    0.239320    0.434244  ...    0.147234

           cg17783401  cg26483332  cg22730412  cg14704921  cg12179661  \
sample_id
GSM990554    0.094635    0.163394    0.304777    0.093110    0.522947
GSM990278    0.043087    0.173311    0.343683    0.029271    0.496056
GSM990589    0.089760    0.173368    0.338127    0.066988    0.484525
GSM990323    0.121145    0.164312    0.394890    0.044809    0.510717
GSM990116    0.035716    0.156062    0.341784    0.024294         NaN

           cg16780603  cg00588614  cg13039082  cg16640358
sample_id
GSM990554    0.736352    0.262954    0.295386    0.350803
GSM990278    0.801962    0.291890    0.288421    0.318693
GSM990589    0.588307    0.276745    0.263589    0.344015
GSM990323    0.736712    0.287274    0.333076    0.303317
GSM990116    0.828072    0.256653    0.322450    0.370363

[5 rows x 1003 columns]


Evaluation set (locked) (100, 1003)            age             ethnicity sex  cg16867657  cg06639320  cg24724428  \
sample_id
GSM990599   65  Caucasian - European   F    0.713534    0.533543    0.338730
GSM989922   76  Caucasian - European   M    0.705395    0.472859    0.310131
GSM990306   63    Hispanic - Mexican   F    0.662773    0.481706    0.237187
GSM990320   59    Hispanic - Mexican   M    0.638065    0.456544    0.174587
GSM990002   71  Caucasian - European   F    0.695067    0.495763    0.276582

           cg07553761  cg22454769  cg06784991  cg21572722  ...  cg17321954  \
sample_id                                                  ...
GSM990599    0.364203    0.662077    0.291724    0.490470  ...    0.237585
GSM989922    0.358959    0.635802    0.287507         NaN  ...    0.206049
GSM990306    0.267787    0.602300    0.306610    0.453492  ...    0.189996
GSM990320    0.281471    0.614537    0.293233    0.436461  ...    0.169437
GSM990002    0.326186    0.662770    0.307118    0.405137  ...    0.176188

           cg17783401  cg26483332  cg22730412  cg14704921  cg12179661  \
sample_id
GSM990599    0.079218    0.165617    0.359383    0.085150    0.570230
GSM989922    0.096464    0.132663    0.280081    0.061219    0.536635
GSM990306    0.070674    0.182137    0.325564    0.052198    0.500524
GSM990320    0.064268    0.199800    0.317769    0.061953    0.528459
GSM990002    0.095870    0.184929    0.270476    0.047256    0.492331

           cg16780603  cg00588614  cg13039082  cg16640358
sample_id
GSM990599    0.800902    0.269018    0.290623    0.314786
GSM989922    0.744812    0.248199    0.262726    0.330051
GSM990306    0.725678    0.298588    0.334402    0.313727
GSM990320    0.748813    0.325457    0.329465    0.363478
GSM990002    0.792136    0.267520         NaN    0.346092

[5 rows x 1003 columns]
Samples of each data: 456 100

In [5]:
#Splitting the data into training and validation sets
#stratifying by age
X=dev_data
y=dev_data["age"]
y_bins=pd.qcut(y,5,duplicates='drop')

# Split the data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y_bins)
total_data=len(X_train) + len(X_val)
train_pre= len(X_train)/ total_data*100
val_pre= len(X_val)/ total_data*100
print("Total samples of dev:",total_data)
print(f"Training set: {len(X_train)} samples ({train_pre:.2f}%)")
print(f"Validation set : {len(X_val)} samples ({val_pre:.2f}%)")

Total samples of dev: 456
Training set: 364 samples (79.82%)
Validation set : 92 samples (20.18%)

In [6]:
#function for splitting
def split_data(dev_data, eval_data):
    X=dev_data.drop(columns=["age"])
    y=dev_data["age"]
    #Bins Creation for stratification
    y_bins=pd.qcut(y,5,duplicates='drop')

    # Split the data
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y_bins)

    train_data=X_train.copy()
    train_data["age"]=y_train

    val_data=X_val.copy()
    val_data["age"]=y_val

    #Percentage Split
    total_data=len(train_data) + len(val_data)
    train_pre= len(train_data)/ total_data*100
    val_pre= len(val_data)/ total_data*100

    '''
    print("Total samples of dev:",total_data)
    print(f"Training set: {len(train_data)} samples ({train_pre:.2f}%)")
    print(f"Validation set : {len(val_data)} samples ({val_pre:.2f}%)")
    '''
    #Creating table of the data split information for better visualization
    table_summary = pd.DataFrame({
    "Split": ["Train", "Validation"],
    "Samples": [len(X_train), len(X_val)],
    "Percentage": [train_pre, val_pre]})
    print(table_summary)
    return train_data,val_data, eval_data

In [7]:
train_data,val_data,eval_data= split_data(dev_data,eval_data)

        Split  Samples  Percentage
0       Train      364   79.824561
1  Validation       92   20.175439

In [8]:
train_data.head(5)

,ethnicity,sex,cg16867657,cg06639320,cg24724428,cg07553761,cg22454769,cg06784991,cg21572722,cg24079702,...,cg17783401,cg26483332,cg22730412,cg14704921,cg12179661,cg16780603,cg00588614,cg13039082,cg16640358,age
sample_id,,,,,,,,,,,,,,,,,,,,,
GSM990121,Hispanic - Mexican,F,0.583677,0.432590,0.251182,0.313086,0.525740,0.265851,0.401995,0.363961,...,0.056080,0.184151,0.360041,0.043045,0.498758,0.742945,0.324369,0.296355,0.325072,64
GSM989978,Caucasian - European,M,0.630068,0.442362,0.258473,0.308090,0.547527,0.255296,0.418272,0.360343,...,0.092445,0.135585,0.320368,0.035074,0.478599,0.800113,0.261482,0.281599,0.324700,54
GSM990621,Caucasian - European,F,0.735531,0.484551,0.306418,0.326822,0.600015,0.279091,0.497256,0.402608,...,0.056014,0.159652,0.263493,0.065471,0.505322,0.736245,0.273843,0.282737,0.341408,70
GSM990064,Caucasian - European,M,0.804368,0.471031,0.330772,0.350285,0.653938,0.362480,0.464412,0.451967,...,0.262035,0.095317,0.256310,0.230947,0.431356,0.778582,0.237803,0.277310,0.293257,83
GSM990488,Hispanic - Mexican,M,0.654641,0.447308,0.244698,0.284639,0.584898,0.270158,0.442787,0.374594,...,0.102901,0.146249,0.326736,0.067682,0.529198,0.756666,0.245583,0.312507,0.326149,68

In [9]:
X_train.head(5)

,age,ethnicity,sex,cg16867657,cg06639320,cg24724428,cg07553761,cg22454769,cg06784991,cg21572722,...,cg17321954,cg17783401,cg26483332,cg22730412,cg14704921,cg12179661,cg16780603,cg00588614,cg13039082,cg16640358
sample_id,,,,,,,,,,,,,,,,,,,,,
GSM990121,64,Hispanic - Mexican,F,0.583677,0.432590,0.251182,0.313086,0.525740,0.265851,0.401995,...,0.198703,0.056080,0.184151,0.360041,0.043045,0.498758,0.742945,0.324369,0.296355,0.325072
GSM989978,54,Caucasian - European,M,0.630068,0.442362,0.258473,0.308090,0.547527,0.255296,0.418272,...,0.172218,0.092445,0.135585,0.320368,0.035074,0.478599,0.800113,0.261482,0.281599,0.324700
GSM990621,70,Caucasian - European,F,0.735531,0.484551,0.306418,0.326822,0.600015,0.279091,0.497256,...,0.194529,0.056014,0.159652,0.263493,0.065471,0.505322,0.736245,0.273843,0.282737,0.341408
GSM990064,83,Caucasian - European,M,0.804368,0.471031,0.330772,0.350285,0.653938,0.362480,0.464412,...,0.223823,0.262035,0.095317,0.256310,0.230947,0.431356,0.778582,0.237803,0.277310,0.293257
GSM990488,68,Hispanic - Mexican,M,0.654641,0.447308,0.244698,0.284639,0.584898,0.270158,0.442787,...,0.181087,0.102901,0.146249,0.326736,0.067682,0.529198,0.756666,0.245583,0.312507,0.326149

In [ ]:
#Searching for the NA values in each data set
print("Missing values in development set")
check_missing_values(dev_data)
print("Missing values in TRAIN set")
check_missing_values(X_train)
print("Missing values in VALIDATION set")
check_missing_values(X_val)
print("Missing values in EVALUATION set")
check_missing_values(eval_data)